services:
  db:
    container_name: acalcmsdb
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=acal
      - POSTGRES_PASSWORD=acal
      - POSTGRES_DB=acaldb
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - acalnet

networks:
  acalnet:
    name: acalnet

volumes:
  db: